#!/usr/bin/env bash
#
#  Note: this script requires passwordless access to
#        poweroff, reboot, pm-suspend and pm-hibernate
#


lock() {
#  killall compton
  $HOME/.config/i3lock/i3lock.sh
#  compton -b
}

case "$1" in
  lock)
    lock
    ;;
  logout)
    i3-msg exit
    ;;
  suspend)
    systemctl suspend
    ;;
  hibernate)
    systemctl hibernate
    ;;
  reboot)
    systemctl reboot
    ;;
  shutdown)
    systemctl poweroff
    ;;
  *)
    echo "Usage: $0 [lock|logout|suspend|hibernate|reboot|shutdown]"
    exit 2
esac

exit 0
